version: "3.8"

services:
  mysql-tc-grupo8:
    image: mysql:8.3
    container_name: container-mysql-tc-grupo8
    ports:
      - "3306:3306"
    networks:
      - tc-grupo8-net
    environment:
      MYSQL_ROOT_PASSWORD: rootAdm123
      MYSQL_DATABASE: db-tc-grupo8
      MYSQL_USER: adm123
      MYSQL_PASSWORD: adm123
    command: --default-authentication-plugin=mysql_native_password

  ms-login:
    build:
      context: ./ms-login
      dockerfile: Dockerfile
    container_name: container-ms-login
    ports:
      - "9207:9207"
    depends_on:
      - mysql-tc-grupo8
    networks:
      - tc-grupo8-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tc-grupo8:3306/db-tc-grupo8?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: adm123
      SPRING_DATASOURCE_PASSWORD: adm123

  ms-usuario:
    build:
      context: ./ms-usuario
      dockerfile: Dockerfile
    container_name: container-ms-usuario
    ports:
      - "9808:9808"
    depends_on:
      - mysql-tc-grupo8
    networks:
      - tc-grupo8-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tc-grupo8:3306/db-tc-grupo8?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: adm123
      SPRING_DATASOURCE_PASSWORD: adm123

  ms-cardapio:
    build:
      context: ./ms-cardapio
      dockerfile: Dockerfile
    container_name: container-ms-cardapio
    ports:
      - "9909:9909"
    depends_on:
      - mysql-tc-grupo8
    networks:
      - tc-grupo8-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tc-grupo8:3306/db-tc-grupo8?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: adm123
      SPRING_DATASOURCE_PASSWORD: adm123

networks:
  tc-grupo8-net:
    driver: bridge
